image: ghcr.io/evandcoleman/{machine}-homeassistant
build_from:
  amd64: "ghcr.io/evandcoleman/amd64-homeassistant:"
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/home-assistant/core
